-- 令和8年度（2026年）診療報酬改定 対応
-- 施行日: 2026年6月1日

-- 1. 実績項目マスタの追加・更新
INSERT INTO pharma_item_master (code, name, unit, description) VALUES
  ('zanryaku_yugai_count', '調剤時残薬調整・薬学的有害事象等防止加算算定件数', '件', '処方箋1万枚当たりの実績計算用'),
  ('gairai_fukuyaku_count', '外来服薬支援料１算定件数', '件', ''),
  ('fukuyaku_info_count', '服薬情報等提供料相当実績', '件', ''),
  ('shouni_tokutei_count', '小児特定加算算定件数', '件', ''),
  ('renkei_kaigi_count', '地域多職種連携会議出席（薬局当たり年間）', '回', '研修認定薬剤師の出席回数'),
  ('zaitaku_visit_kojinka', '在宅患者訪問（個人宅）件数', '件', '単一建物1人の在宅薬剤管理'),
  ('kohatsu_ratio', '後発医薬品調剤割合', '%', '地域支援・医薬品供給対応体制加算の施設基準')
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  unit = EXCLUDED.unit,
  description = EXCLUDED.description;

-- 2. 店舗に調剤基本料区分を追加（加算2・3 vs 4・5の判定用）
ALTER TABLE pharma_pharmacies
  ADD COLUMN IF NOT EXISTS chozai_kihon INTEGER DEFAULT 1 CHECK (chozai_kihon IN (1, 2, 3));
COMMENT ON COLUMN pharma_pharmacies.chozai_kihon IS '1=調剤基本料1, 2=調剤基本料2, 3=調剤基本料3（地域支援加算2・3は1のみ、4・5は2・3）';

-- 3. 2026年改定の加算マスタ（最新版のみ。旧2024年加算は残すが、画面では2026を優先表示）
-- 地域支援・医薬品供給対応体制加算（処方箋1万枚当たりの実績は kasan-recalc で計算）
-- 在宅薬学総合体制加算・電子的調剤情報連携体制整備加算
INSERT INTO pharma_kasan_master (code, revision_year, name, points, effective_from, requirements_json) VALUES
  ('chiiki_iryo_1', 2026, '地域支援・医薬品供給対応体制加算１', 27, '2026-06-01', '{"condition_groups":[{"id":"kohatsu","logic":"AND","items":[{"code":"kohatsu","name":"後発医薬品調剤割合85%以上","type":"metric","metric_code":"kohatsu_ratio","threshold":{"value":85,"period":"month","operator":">="}}]},{"id":"junkai","logic":"AND","items":[{"code":"junkai_chiiki_iryo","name":"地域支援・医薬品供給対応体制加算の届出","type":"approval"}]}]}'::jsonb),
  ('chiiki_iryo_2', 2026, '地域支援・医薬品供給対応体制加算２', 59, '2026-06-01', '{"condition_groups":[{"id":"base","logic":"AND","items":[{"code":"chozai_1","name":"調剤基本料１の薬局","type":"approval"},{"code":"kohatsu","name":"後発医薬品調剤割合85%以上","type":"metric","metric_code":"kohatsu_ratio","threshold":{"value":85,"period":"month","operator":">="}}]},{"id":"jisseki","logic":"AND","min_count":3,"items":[{"code":"zanryaku","name":"③残薬調整・有害事象 20回以上/万枚","type":"metric","metric_code":"zanryaku_yugai_per_man","threshold":{"value":20,"period":"year","operator":">="}},{"code":"kakaritsuke","name":"④かかりつけ 20回以上/万枚","type":"metric","metric_code":"kakaritsuke_per_man","threshold":{"value":20,"period":"year","operator":">="}},{"code":"zaitaku","name":"⑥在宅薬剤管理 24回以上/万枚","type":"metric","metric_code":"zaitaku_per_man","threshold":{"value":24,"period":"year","operator":">="}}]}]}'::jsonb),
  ('chiiki_iryo_3', 2026, '地域支援・医薬品供給対応体制加算３', 67, '2026-06-01', '{"condition_groups":[{"id":"base","logic":"AND","items":[{"code":"chozai_1","name":"調剤基本料１の薬局","type":"approval"},{"code":"kohatsu","name":"後発医薬品調剤割合85%以上","type":"metric","metric_code":"kohatsu_ratio","threshold":{"value":85,"period":"month","operator":">="}}]},{"id":"jisseki","logic":"AND","min_count":7,"items":[{"code":"jikangai","name":"①夜間休日対応 40回以上/万枚","type":"metric","metric_code":"jikangai_per_man","threshold":{"value":40,"period":"year","operator":">="}},{"code":"mayaku","name":"②麻薬調剤 1回以上/万枚","type":"metric","metric_code":"mayaku_per_man","threshold":{"value":1,"period":"year","operator":">="}},{"code":"zanryaku","name":"③残薬調整・有害事象 20回以上/万枚","type":"metric","metric_code":"zanryaku_yugai_per_man","threshold":{"value":20,"period":"year","operator":">="}},{"code":"kakaritsuke","name":"④かかりつけ 20回以上/万枚","type":"metric","metric_code":"kakaritsuke_per_man","threshold":{"value":20,"period":"year","operator":">="}},{"code":"gairai","name":"⑤外来服薬支援 1回以上/万枚","type":"metric","metric_code":"gairai_fukuyaku_per_man","threshold":{"value":1,"period":"year","operator":">="}},{"code":"zaitaku","name":"⑥在宅薬剤管理 24回以上/万枚","type":"metric","metric_code":"zaitaku_per_man","threshold":{"value":24,"period":"year","operator":">="}},{"code":"fukuyaku_info","name":"⑦服薬情報提供 30回以上/万枚","type":"metric","metric_code":"fukuyaku_info_per_man","threshold":{"value":30,"period":"year","operator":">="}},{"code":"shouni","name":"⑧小児特定 1回以上/万枚","type":"metric","metric_code":"shouni_tokutei_per_man","threshold":{"value":1,"period":"year","operator":">="}},{"code":"renkei","name":"⑨多職種連携会議 1回以上/年","type":"metric","metric_code":"renkei_kaigi_count","threshold":{"value":1,"period":"year","operator":">="}}]}]}'::jsonb),
  ('chiiki_iryo_4', 2026, '地域支援・医薬品供給対応体制加算４', 37, '2026-06-01', '{"condition_groups":[{"id":"base","logic":"AND","items":[{"code":"chozai_23","name":"調剤基本料２または３の薬局","type":"approval"},{"code":"kohatsu","name":"後発医薬品調剤割合85%以上","type":"metric","metric_code":"kohatsu_ratio","threshold":{"value":85,"period":"month","operator":">="}}]},{"id":"jisseki","logic":"AND","min_count":3,"items":[{"code":"zanryaku","name":"③残薬調整・有害事象 40回以上/万枚","type":"metric","metric_code":"zanryaku_yugai_per_man","threshold":{"value":40,"period":"year","operator":">="}},{"code":"kakaritsuke","name":"④かかりつけ 40回以上/万枚","type":"metric","metric_code":"kakaritsuke_per_man","threshold":{"value":40,"period":"year","operator":">="}},{"code":"zaitaku","name":"⑥在宅薬剤管理 24回以上/万枚","type":"metric","metric_code":"zaitaku_per_man","threshold":{"value":24,"period":"year","operator":">="}}]}]}'::jsonb),
  ('chiiki_iryo_5', 2026, '地域支援・医薬品供給対応体制加算５', 59, '2026-06-01', '{"condition_groups":[{"id":"base","logic":"AND","items":[{"code":"chozai_23","name":"調剤基本料２または３の薬局","type":"approval"},{"code":"kohatsu","name":"後発医薬品調剤割合85%以上","type":"metric","metric_code":"kohatsu_ratio","threshold":{"value":85,"period":"month","operator":">="}}]},{"id":"jisseki","logic":"AND","min_count":7,"items":[{"code":"jikangai","name":"①夜間休日対応 400回以上/万枚","type":"metric","metric_code":"jikangai_per_man","threshold":{"value":400,"period":"year","operator":">="}},{"code":"mayaku","name":"②麻薬調剤 10回以上/万枚","type":"metric","metric_code":"mayaku_per_man","threshold":{"value":10,"period":"year","operator":">="}},{"code":"zanryaku","name":"③残薬調整・有害事象 40回以上/万枚","type":"metric","metric_code":"zanryaku_yugai_per_man","threshold":{"value":40,"period":"year","operator":">="}},{"code":"kakaritsuke","name":"④かかりつけ 40回以上/万枚","type":"metric","metric_code":"kakaritsuke_per_man","threshold":{"value":40,"period":"year","operator":">="}},{"code":"gairai","name":"⑤外来服薬支援 12回以上/万枚","type":"metric","metric_code":"gairai_fukuyaku_per_man","threshold":{"value":12,"period":"year","operator":">="}},{"code":"zaitaku","name":"⑥在宅薬剤管理 24回以上/万枚","type":"metric","metric_code":"zaitaku_per_man","threshold":{"value":24,"period":"year","operator":">="}},{"code":"fukuyaku_info","name":"⑦服薬情報提供 60回以上/万枚","type":"metric","metric_code":"fukuyaku_info_per_man","threshold":{"value":60,"period":"year","operator":">="}},{"code":"shouni","name":"⑧小児特定 1回以上/万枚","type":"metric","metric_code":"shouni_tokutei_per_man","threshold":{"value":1,"period":"year","operator":">="}},{"code":"renkei","name":"⑨多職種連携会議 5回以上/年","type":"metric","metric_code":"renkei_kaigi_count","threshold":{"value":5,"period":"year","operator":">="}}]}]}'::jsonb),
  ('zaitaku_sogo_1', 2026, '在宅薬学総合体制加算１', 30, '2026-06-01', '{"condition_groups":[{"id":"zaitaku_junkai","logic":"AND","items":[{"code":"zaitaku_junkai","name":"在宅患者訪問薬剤管理指導の届出","type":"approval"}]},{"id":"jisseki","logic":"AND","items":[{"code":"zaitaku_48","name":"訪問薬剤管理指導実績 48回以上/年","type":"metric","metric_code":"zaitaku_visit","threshold":{"value":48,"period":"year","operator":">="}}]}]}'::jsonb),
  ('zaitaku_sogo_2', 2026, '在宅薬学総合体制加算２', 100, '2026-06-01', '{"condition_groups":[{"id":"base","logic":"AND","items":[{"code":"zaitaku_sogo_1","name":"加算１の施設基準を満たす","type":"approval"}]},{"id":"jisseki","logic":"OR","min_count":1,"items":[{"code":"pattern_a","name":"ア 個人宅240回以上/年（個人宅2割以上）","type":"metric","metric_code":"zaitaku_visit_kojinka","threshold":{"value":240,"period":"year","operator":">="}},{"code":"pattern_b","name":"イ 総訪問480回以上/年（個人宅1割以上）","type":"metric","metric_code":"zaitaku_visit","threshold":{"value":480,"period":"year","operator":">="}}]}]}'::jsonb),
  ('denshi_chozai_renkei', 2026, '電子的調剤情報連携体制整備加算', 8, '2026-06-01', '{"condition_groups":[{"id":"mynumber","logic":"AND","items":[{"code":"mynumber_30","name":"マイナ保険証利用率 30%以上","type":"metric","metric_code":"mynumber_confirm_pct","threshold":{"value":30,"period":"month","operator":">="}}]}]}'::jsonb)
ON CONFLICT (code, revision_year) DO UPDATE SET
  name = EXCLUDED.name,
  points = EXCLUDED.points,
  effective_from = EXCLUDED.effective_from,
  requirements_json = EXCLUDED.requirements_json;
